[project]
name = "qppte"
dynamic = ["version"]
description = "QPlainTextEdit with Python syntax highlighting"
readme = "README.md"
authors = [
    { name = "Dmitri Priimak", email = "priimak@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.11.1",
    "tree-sitter>=0.26.0",
    "tree-sitter-python>=0.25.0",
]

[project.scripts]
qppte_demo = "qppte.example_gui:main"

[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "W", # pycodestyle
    "B", # flake8-bugbear
    "I", # isort
]

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]
