[project]
name = "qppte"
version = "0.1.0"
description = "QPlainTextEdit with Python syntax highlighting"
readme = "README.md"
authors = [
    { name = "Dmitri Priimak", email = "priimak@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.11.1",
    "tree-sitter==0.26.0",
    "tree-sitter-python>=0.25.0",
]

[project.scripts]
qppte = "qppte:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"


[tool.setuptools-git-versioning]
enabled = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "W", # pycodestyle
    "B", # flake8-bugbear
    "I", # isort
]

[tool.uv.sources]
tree-sitter = { path = "/home/priimak/git/py-tree-sitter/dist/tree_sitter-0.26.0-cp313-cp313-linux_x86_64.whl" }

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]

